<div class="blog-page main grid-wrap">

		<header class="grid col-full">
			<hr>
			<p class="fleft">Blog</p>
		</header>
		
				
		<section class="grid col-three-quarters mq2-col-two-thirds mq3-col-full">
					<?php foreach ($this->blog as  $blog): ?>
			<article class="post">
				<h2><a href="post.html" class="post-title"><?php echo $blog['title'] ?></a></h2>
                                <hr>
                                <div class="meta">
				</div>
				<div class="entry">
                                   <p> <?php echo $blog['content'] ?> </p>
                                   <?php endforeach ?>
				<footer>
					<a href="post.html" class="more-link">Czytaj więcej</a>
				</footer>
			</article>
		
			<ul class="page-numbers">
				<li><a href="#">Prev</a></li>
				<li><a href="#" class="current">1</a></li>
				<li><a href="#">2</a></li>
				<li><a href="#">3</a></li>
				<li><a href="#">4</a></li>
				<li><a href="#">Next</a></li>
			</ul>
		
		</section>

		<aside class="grid col-one-quarter mq2-col-one-third mq3-col-full blog-sidebar">
				
			<div class="widget">
				<input id="search" type="search" name="search" value="Type and hit enter to search" >
			</div>
			
			<div class="widget">
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim.</p>
			</div>
			
			<div class="widget">
			<h2>Popular Posts</h2>
			<ul>
				<li><a href="#" title="">Nullam porttitor elementum ligula</a></li>
				<li><a href="#" title="">Vestibulum interdum</a></li>	
				<li><a href="#" title="">Quisque venenatis ante sit amet dolor</a></li>		
				<li><a href="#" title="">Aliquam adipiscing libero vitae leo</a></li>		
				<li><a href="#" title="">Sed accumsan quam ac tellus</a></li>	
			</ul>
			</div>
			
			<div class="widget">
			<h2>Categories</h2>
			<ul>
			 	<li><a href="http://">Design (99+)</a></li>
				<li><a href="http://">Web (53)</a></li>
				<li><a href="http://">Other (12)</a></li>
				<li><a href="http://">Weird (4)</a></li>
			</ul>
			</div>
		
			<div class="widget">
			<h2>Meta</h2>
			<ul>
				<li><a href="">Entries (RSS)</a></li>
				<li><a href="">Comments (RSS)</a></li>
			</ul>
			</div>
		</aside>

		
		
		
	</div> <!--main-->