<div class="home-page main">
	<section class="grid-wrap" >
		<header class="grid col-full">
			<hr>
			<p class="fleft">Główna</p>
			<a href="onas.html" class="arrow fright">przeczytaj więcej</a>
		</header>
		
		<div class="grid col-one-half mq2-col-full">
                     <?php foreach ($this->glowna as $k => $glowna): ?>
			<h2><?php echo $glowna['glownacol'] ?></h2>
			<p><?php echo $glowna['glownacol1'] ?></p>
			<?php endforeach ?> 
            		</div>
			
	
		 <div class="slider grid col-one-half mq2-col-full">
		   <div class="flexslider">
		     <div class="slides">
		       <div class="slide">
		           	<figure>
		                 <img src="img/img2.jpg" alt="">
		                 <figcaption>
		                 	<div>
		                 	<h5>Caption 1</h5>
		                 	<p>Lorem ipsum dolor set amet, lorem, <a href="#">link text</a></p>
		                 	</div>
		                 </figcaption>
		             	</figure>
		           </div>
		           
		           <div class="slide">
		               	<figure>
		                     <img src="img/img.jpg" alt="">
		                     <figcaption>
		                     	<div>
		                     	<h5>Caption 2</h5>
		                     	<p>Fusce dapibus, tellus ac cursus commodo, tortor mauris condimentum nibh.</p>
		                     	</div>
		                     </figcaption>
		                 	</figure>
		               </div>
		            </div>
		   </div>
		 </div>
		
		 </section>
	
	<section class="services grid-wrap">
		<header class="grid col-full">
			<hr>
			<p class="fleft">Oferta</p>
			<a href="oferta.html" class="arrow fright">zapoznaj sie znaszą ofertą</a>
		</header>
		
		<article class="grid col-one-third mq3-col-full">
			<aside>01</aside>
			<h5>Strony Internetowe</h5>
			<p>W obecnych czasach strona internetowa, to podstawowe źródło informacji o produkcie, 
				ofercie, czy nawet miejscu, strony internetwe to również potężne narzędzie marketingowe, 
				sklepy internetowe, wizytówki www, systemy cms. Nasza firma posiada własną serwerownie, oraz jest rejestratorem domen dzięki czemu możemy proponować kąpleksowe rozwiązania w konkurencyjnych cenach.</p>
		</article>
		
		<article class="grid col-one-third mq3-col-full">
			<aside>02</aside>
			<h5>Aplikacje Internetowe</h5>
			<p>Pod tym pojęciem kryje się, bardzo wiele aspektów, od tworzenia systemów kontaktowych, formularzy zamówień po systemy czatu online dla klientów, jak również systemów crm, sklepów internetowych, blogów, systemów bazodanowych.</p>
		</article>
		
		<article class="grid col-one-third mq3-col-full">
			<aside>03</aside>
			<h5>Pozycjonowanie stron www</h5>
			<p>Głównym zadaniem, pozycjonowania strony w wyszukiwarkach jest, pozyskanie klientów, dzięki stosowaniu tego typu reklamy mamy szansę trafić z ofertą do większej liczby potęcjalnych klientów, dzięki 15 letniemu doświadczeniu w technologiach interentowych, wiemy jak sprawić by Państwa strona internetowa znalazła się w czołówkach wyszukiwarek.</p>
		</article>
	</section>

<section class="works grid-wrap">
	<header class="grid col-full">
			<hr>
			<p class="fleft">Nasz prace</p>
			<a href="works.html" class="arrow fright">zobacz więcej prac</a>
		</header>
	
			<figure class="grid col-one-quarter mq2-col-one-half">
				<a href="work1.html">
				<img src="img/img.jpg" alt="">
				<span class="zoom"></span>
				</a>
				<figcaption>
					<a href="work1.html" class="arrow">Project page!</a>
					<p>Lorem ipsum dolor set amet</p>
				</figcaption>
			</figure>

			<figure class="grid col-one-quarter mq2-col-one-half">
				<a href="#">
				<img src="img/img.jpg" alt="">
				<span class="zoom"></span>
				</a>
				<figcaption>
					<a href="#" class="arrow">Project x</a>
					<p>Lorem ipsum dolor set amet</p>
				</figcaption>
			</figure>
		
			<figure class="grid col-one-quarter mq2-col-one-half">
				<a href="#">
				<img src="img/img.jpg" alt="">
				<span class="zoom"></span>
				</a>
				<figcaption>
					<a href="#" class="arrow">Project x</a>
					<p>Lorem ipsum dolor set amet</p>
				</figcaption>
			</figure>
		
			<figure class="grid col-one-quarter mq2-col-one-half">
				<a href="#">
				<img src="img/img.jpg" alt="">
				<span class="zoom"></span>
				</a>
				<figcaption>
					<a href="#" class="arrow">Project x</a>
					<p>Lorem ipsum dolor set amet</p>
				</figcaption>
			</figure>
	</section>
	</div> <!--main-->