<div class="contact-page main grid-wrap">

		<header class="grid col-full">
			<hr>
			<p class="fleft">Kontakt </p>
		</header>

		
		
		<aside class="grid col-one-quarter mq2-col-one-third mq3-col-full">

			<p class="mbottom">Z wielką przyjemnością odpowiemy na wasze pytania</p>
			
			<address class="mbottom">
				<h5>REINFO-SERWIS </h5>
				ul. Marcinkowicka 125 <br >
				33-395 Chełmiec <br >
				<br >
				<a href="http://maps.google.com">Get directions</a>
			</address>
		
			<p class="mbottom">
				+48. 535-766-735<br >
				00 77 66 55 33</p>
			<p class="mbottom">
				<a href="#">biuro@reinfo-serwis.pl</a><br >
				<a href="#">strony@reinfo-serwis.plk</a><br >
				<a href="#">@designstudio on Twitter</a><br >
				<a href="#">Designa Studio on Google+</a>
			</p>
			<p>
				<h6>Zapraszamy w godzinach : </h6>
				Poniedziałek - Piątek <br >
				od 9:00 do 17:00
			</p>
		
		</aside>
		
		<section class="grid col-three-quarters mq2-col-two-thirds mq3-col-full">
			<h2>Napisz do nas</h2>
			<p class="warning">Don't forget to put your own email address in the php file!</p>
			
			<form id="contact_form" class="contact_form" action="contact.php" method="post" name="contact_form">	
				<ul>
					<li>
						<label for="name">Imię nazwisko / Nazwa firmy:</label>
						<input type="text" name="name" id="name" required class="required" >
					</li>
					<li>
						<label for="email">Adres email:</label>
						<input type="email" name="email" id="email" required placeholder="twój-email@gmail.com" class="required email">
					</li>	
					<li>
						<label for="message">Wiadomość:</label>
						<textarea name="message" id="message" cols="100" rows="6" required  class="required" ></textarea>
					</li>
					<li>
						<button type="submit" id="submit" name="submit" class="button fright">Wyślij</button>
					</li>	
				</ul>			
			</form>
		</section>	
		
	</div> 