<div class="services-page main grid-wrap">

		<header class="grid col-full">
			<hr>
			<p class="fleft">Oferta</p>
		</header>


		<aside class="grid col-one-quarter mq2-col-full">
			<p class="mbottom">Drogi internauto z przyjemnością opowiemy Ci o tym czym się zajmujemy.
			</p>
		<!--	<menu>
				<ul>
					<li><a href="#navbutton" class="arrow">Buttons</a></li>
					<li><a href="#navtogg" class="arrow">Toggles</a></li>
					<li><a href="#navtabs" class="arrow">Tabs</a></li>
				</ul>
		</menu> -->
		</aside>
		
		<section class="grid col-three-quarters mq2-col-full">
		
			
			
			<div class="grid-wrap">
		<!--	
			<article id="navbutton" class="grid col-full">
				<h2>Oferta</h2>
				<p>
					<a href="#" class="button">Strony Internetowe</a>
					<a href="#" class="button">Aplikacje Internetowe</a>
					<a href="#" class="button">Hostin www</a>
					<a href="#" class="button">Pozycjonowanie</a>
				</p>
			</article> -->
		
			<article id="navtogg" class="grid col-full">
			<!--	<h2>Toggles</h2>
						<ul class="toggle-view">
							<li>
								<h5 class="toggle-title">General <span class="toggle-title-detail">- Main features</span></h5>
								<div class="toggle grid-wrap">                     
									<ul class="grid col-one-half mq3-col-full">
										<li>Lorem ipsum</li>
										<li>Cras</li>
										<li>Dolor Euismod Cras</li>
										<li>Sit Amet</li>
										<li>Ornare Nullam Dolor</li> 
										<li>Consectetur</li>
									</ul>
									<ul class="grid col-one-half mq3-col-full">
										<li>Euismod Dapibus</li>
										<li>Magna</li>
										<li>Lorem Ligula Elit</li>
										<li>Dolor Vulputate</li>
										<li>Dapibus</li> 
										<li>Dolor Mattis Ipsum</li>
									</ul>
								</div>       
							</li>
							
							<li>
								<h5 class="toggle-title">Lorem <span class="toggle-title-detail">- Ipsum dolor</span></h5>
								<div class="toggle">                     
									<p>Etiam porta sem malesuada magna mollis euismod. Nulla vitae elit libero, a pharetra augue. Sed posuere consectetur est at lobortis. Sed posuere consectetur est at lobortis. Aenean eu leo quam. Pellentesque ornare sem lacinia quam venenatis vestibulum. Donec sed odio dui.</p>
								</div>       
							</li>
						</ul>
			</article> -->
			
			<article id="navtabs" class="grid col-full">
				<h2></h2>
				<div class="">
					<ul class="tabs clearfix">
					    <li><a href="#tab1">Strony Internetowe</a></li>
					    <li><a href="#tab2">Aplikacje Internetowe</a></li>
					    <li><a href="#tab3">Hostin www</a></li>
					    <li><a href="#tab4">Pozycjonowanie</a></li>
					</ul>
					<div class="tab_container">
					    <article id="tab1" class="tab_content">
					        <p>Stworzymy praktycznie każdą stronę internetową o prostej wizytówki inetrnetowej opartej na html5 oraz css3 po złożony system zarządzania treścią zwany potocznie cms, każdy szablon wygląd strony jest omawiany z klientem, 
					        	nasi pracownicy oceniają branżę w jakiej ma działać stron i dobierają 
					        	grafikę oraz kolorystykę strony pod klienta działalność, dzięki czemu powstaje nie 
					        	powtarzalny projekt graficzny czytelny i zarazem przejrzysty.</p>
					    </article>
					    
						<article id="tab2" class="tab_content">
							<h6>Aplikacje Internetowe</h6>
					        <p>Stworzymy to czegi inni nie chcą zrobić, bardzo często się zdarza że klient posiada już działającą stronę,
					        	 i chciałby ją rozbudować ją o nowe możliwości, tu z pomocą przychodzimy my. 
					        	 Stworzymy każdą aplikację internetową działając po stronie serwer od prostych formularzy po złożone systemy crm, pracujemy w najlepszych frameworkach php5,
					        	 oraz w nowoczesnych językach programowania dzięki czemu nasze produjty są na najwyszym poziomie.</p>
					    
					    <article id="tab3" class="tab_content">
				    		<h6>Hosting stron internetowych</h6>
				            <p>Nasza firma posiada własne serwery dla aplikacji internetowych, dzieki takiemu rozwiązaniu jesteśmy wstanie zaproponować nisze koszta wdrożenia strony internetowej czy aplikacji, nasze serwery obsługują jezyki programowania takie jak PHP5, Ruby & Rails, frameworki PHP - Zendframework2, Symfony2, Kohana,  i wiele wiele innych.</p>
					    </article>
					  <article id="tab4" class="tab_content">
				    		<h6>Hosting stron internetowych</h6>
				            <p>Nasza firma posiada własne serwery dla aplikacji internetowych, dzieki takiemu rozwiązaniu jesteśmy wstanie zaproponować nisze koszta wdrożenia strony internetowej czy aplikacji, nasze serwery obsługują jezyki programowania takie jak PHP5, Ruby & Rails, frameworki PHP - Zendframework2, Symfony2, Kohana,  i wiele wiele innych.</p>
					    </article>
					 </div>
				  </div>
			</article>
			
			</div> <!-- 100%articles-->
		
		</section>	
		
		
		
	</div> <!--main-->
