<div class="blogpost-page main grid-wrap">

		<header class="grid col-full">
			<hr>
			<p class="fleft">Blog post</p>
		</header>
		
				
		<section class="grid col-three-quarters mq2-col-two-thirds mq3-col-full">
			
				<article class="post post-single">
					<h2><a href="#" class="post-title">Blog post</a></h2>
					<div class="meta">
						<p>Posted on <span class="time">November 15, 2011</span> by <a href="#" class="fn">Sylvain Lafitte</a> in <a href="#"class="cat">Other</a> with <a href="#" class="comments-link">42 comments</a>.</p>
					</div>
					<div class="entry">
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit. Nulla facilisi. Nulla libero. Vivamus pharetra posuere sapien. Nam consectetuer. Sed aliquam, nunc eget euismod ullamcorper, lectus nunc ullamcorper orci, fermentum bibendum enim nibh eget ipsum. Donec porttitor ligula eu dolor. Maecenas vitae nulla consequat libero cursus venenatis. Nam magna enim, accumsan eu, blandit sed, blandit a, eros.</p>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit. Nulla facilisi. Nulla libero. Vivamus pharetra posuere sapien. Nam consectetuer. Sed aliquam, nunc eget euismod ullamcorper, lectus nunc ullamcorper orci, fermentum bibendum enim nibh eget ipsum. Donec porttitor ligula eu dolor. Maecenas vitae nulla consequat libero cursus venenatis. Nam magna enim, accumsan eu, blandit sed, blandit a, eros.</p>
						<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit. Nulla facilisi. Nulla libero. Vivamus pharetra posuere sapien. Nam consectetuer. Sed aliquam, nunc eget euismod ullamcorper, lectus nunc ullamcorper orci, fermentum bibendum enim nibh eget ipsum. Donec porttitor ligula eu dolor. Maecenas vitae nulla consequat libero cursus venenatis. Nam magna enim, accumsan eu, blandit sed, blandit a, eros.</p>
					</div>
					
				</article>
					
				<section class="section-comment">
				
					<header>
						<hr>
						<h5 class="fleft">42 Comments</h5> <p class="fright"><a href="#leavecomment" class="arrow">Leave your comment</a></p>
					</header>
				
					<ol class="comments">
						<li class="comment">
							<h6>John Doe <span class="meta"> on 18/02/12</span></h6>
							<p>Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit.</p>
						</li>
						
						<li class="comment">
							<h6>John Doe <span class="meta"> on 18/02/12</span></h6>
							<p>Nullam sit amet enim. Suspendisse id velit vitae ligula volutpat condimentum. Aliquam erat volutpat. Sed quis velit.</p>
						</li>
						
						<li class="comment">
							<h6>John Doe <span class="meta"> on 18/02/12</span></h6>
							<p>Lorem ipsum dolor set amet.</p>
						</li>
						
						<li class="comment">
							<h6>John Doe <span class="meta"> on 18/02/12</span></h6>
							<p>Vivamus pharetra posuere sapien. Nam consectetuer.</p>
						</li>
						
						<li class="comment">
							<h6>John Doe <span class="meta"> on 18/02/12</span></h6>
							<p>Yep!</p>
						</li>
				
					</ol>
			
					
			<div class="leavecomment" id="leavecomment">
				<h3>Leave your comment</h3>
				<form id="#" class="#" action="#" method="post" name="#">
					<ul>
						<li>
							<label for="name">Your name:</label>
							<input type="text" name="name" id="name" required class="required" >
						</li>
						<li>
							<label for="email">Email:</label>
							<input type="email" name="email" id="email" required placeholder="JohnDoe@gmail.com" class="required email">
						</li>	
						<li>
							<label for="message">Message:</label>
							<textarea name="message" id="message" cols="100" rows="6" required  class="required" ></textarea>
						</li>
						<li>
							<button type="submit" id="submit" class="button fright">Send it</button>
						</li>	
					</ul>			
				</form>
			</div>
				
		</section>
			
		
		</section>

		<aside class="grid col-one-quarter mq2-col-one-third mq3-col-full blog-sidebar">
				
			<div class="widget">
			<input id="search" type="search" name="search" value="Type and hit enter to search" >
			</div>
			
			<div class="widget">
			<p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Morbi commodo, ipsum sed pharetra gravida, orci magna rhoncus neque, id pulvinar odio lorem non turpis. Nullam sit amet enim.</p>
			</div>
			
			<div class="widget">
			<h2>Popular Posts</h2>
			<ul>
				<li><a href="#" title="">Nullam porttitor elementum ligula</a></li>
				<li><a href="#" title="">Vestibulum interdum</a></li>	
				<li><a href="#" title="">Quisque venenatis ante sit amet dolor</a></li>		
				<li><a href="#" title="">Aliquam adipiscing libero vitae leo</a></li>		
				<li><a href="#" title="">Sed accumsan quam ac tellus</a></li>	
			</ul>
			</div>
			
			<div class="widget">
			<h2>Categories</h2>
			<ul>
			 	<li><a href="http://">Design (99+)</a></li>
				<li><a href="http://">Web (53)</a></li>
				<li><a href="http://">Other (12)</a></li>
				<li><a href="http://">Weird (4)</a></li>
			</ul>
			</div>
		
			<div class="widget">
			<h2>Meta</h2>
			<ul>
				<li><a href="">Entries (RSS)</a></li>
				<li><a href="">Comments (RSS)</a></li>
			</ul>
			</div>
		</aside>
	
		
	</div> 
